@echo off
echo Iniciando OpenCode Planner en Docker...
docker-compose up -d
echo Esperando a que el servidor este listo (5 segundos)...
timeout /t 5
echo Abriendo navegador en modo App...
start chrome --start-fullscreen --app=http://localhost:8000/produccion/planificacion/visual/
