# Generated by Django 5.2.7 on 2025-12-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaConfig',
            fields=[
                ('id_maquina', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID de Máquina')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Máquina')),
            ],
            options={
                'verbose_name': 'Configuración de Máquina',
                'verbose_name_plural': 'Configuraciones de Máquinas',
                'db_table': 'maquina_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HorarioMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LV', 'Lunes a Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=2, verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='produccion.maquinaconfig')),
            ],
            options={
                'verbose_name': 'Horario de Máquina',
                'verbose_name_plural': 'Horarios de Máquinas',
                'db_table': 'horario_maquina',
                'managed': True,
                'unique_together': {('maquina', 'dia')},
            },
        ),
    ]
