# Generated by Django 5.2.7 on 2025-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_maquinaconfig_horariomaquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridadmanual',
            name='prioridad',
            field=models.FloatField(default=0.0),
        ),
    ]
