# Generated by Django 5.2.7 on 2025-12-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_alter_prioridadmanual_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('se_planifica', models.BooleanField(default=False, help_text='Marcar si este feriado se trabaja y debe incluirse en la planificación', verbose_name='Se Planifica')),
                ('activo', models.BooleanField(default=True, help_text='Feriados inactivos no se consideran en la planificación', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'feriado',
                'ordering': ['fecha'],
                'managed': True,
            },
        ),
    ]
