# Generated by Django 5.2.7 on 2025-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_feriado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tman002',
        ),
        migrations.DeleteModel(
            name='Tman006',
        ),
        migrations.DeleteModel(
            name='Tman007',
        ),
        migrations.DeleteModel(
            name='Tman010',
        ),
        migrations.DeleteModel(
            name='Tman050',
        ),
        migrations.AlterModelOptions(
            name='horariomaquina',
            options={'managed': True, 'verbose_name': 'Horario de Maquina', 'verbose_name_plural': 'Horarios de Maquinas'},
        ),
        migrations.AlterModelOptions(
            name='maquinaconfig',
            options={'managed': True, 'verbose_name': 'Configuracion de Maquina', 'verbose_name_plural': 'Configuraciones de Maquinas'},
        ),
        migrations.RemoveField(
            model_name='feriado',
            name='se_planifica',
        ),
        migrations.AddField(
            model_name='feriado',
            name='tipo_jornada',
            field=models.CharField(choices=[('NO', 'No se trabaja'), ('MEDIO', 'Medio dia'), ('SI', 'Se trabaja')], default='NO', help_text='Indica si se trabaja, medio dia o no se trabaja', max_length=5, verbose_name='Tipo de Jornada'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Feriados inactivos no se consideran en la planificacion', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Modificacion'),
        ),
        migrations.AlterField(
            model_name='horariomaquina',
            name='dia',
            field=models.CharField(choices=[('LV', 'Lunes a Viernes'), ('SA', 'Sabado'), ('DO', 'Domingo')], max_length=2, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='maquinaconfig',
            name='id_maquina',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID de Maquina'),
        ),
        migrations.AlterField(
            model_name='maquinaconfig',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de Maquina'),
        ),
    ]
