# Generated by Django 5.2.7 on 2025-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_delete_tman002_delete_tman006_delete_tman007_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor_id', models.BigIntegerField(db_column='PredecessorId', verbose_name='Tarea Predecesora')),
                ('successor_id', models.BigIntegerField(db_column='SuccessorId', verbose_name='Tarea Sucesora')),
            ],
            options={
                'verbose_name': 'Dependencia de Tarea',
                'verbose_name_plural': 'Dependencias de Tareas',
                'db_table': 'task_dependency',
                'managed': True,
                'unique_together': {('predecessor_id', 'successor_id')},
            },
        ),
    ]
