# Generated by Django 5.2.7 on 2025-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_taskdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenTask',
            fields=[
                ('id_orden', models.BigIntegerField(db_column='IdOrden', primary_key=True, serialize=False, verbose_name='ID de Orden')),
                ('fecha_oculto', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarea Oculta',
                'verbose_name_plural': 'Tareas Ocultas',
                'db_table': 'hidden_task',
                'managed': True,
            },
        ),
    ]
