# Generated by Django 5.2.7 on 2025-12-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_hiddentask'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadmanual',
            name='tiempo_manual',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo Manual'),
        ),
    ]
