# Generated by Django 5.2.7 on 2025-12-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_prioridadmanual_tiempo_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadmanual',
            name='nivel_manual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel Planificacion Manual'),
        ),
    ]
