# Generated by Django 5.2.7 on 2025-12-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_prioridadmanual_nivel_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadmanual',
            name='porcentaje_solapamiento',
            field=models.FloatField(blank=True, default=0.0, help_text='Porcentaje del lote que debe estar completo antes de iniciar siguiente proceso (0-100)', null=True, verbose_name='% Solapamiento'),
        ),
    ]
