# Generated by Django 5.2.7 on 2025-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_prioridadmanual_porcentaje_solapamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadmanual',
            name='fecha_inicio_manual',
            field=models.DateTimeField(blank=True, help_text='Fecha forzada manualmente por el usuario (Drag & Drop)', null=True, verbose_name='Inicio Manual (Pin)'),
        ),
    ]
