# Generated by Django 4.2.28 on 2026-02-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_prioridadmanual_fecha_inicio_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Plan Oficial', max_length=100, verbose_name='Nombre del Escenario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es Plan Oficial')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escenario de Planificación',
                'verbose_name_plural': 'Escenarios de Planificación',
                'db_table': 'scenario',
                'managed': True,
            },
        ),
        # migrations.AlterUniqueTogether(
        #     name='prioridadmanual',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='prioridadmanual',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='produccion.scenario', verbose_name='Escenario'),
        ),
        migrations.AlterUniqueTogether(
            name='prioridadmanual',
            unique_together={('id_orden', 'maquina', 'scenario')},
        ),
    ]
