# Generated by Django 5.2.11 on 2026-02-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_scenario_alter_prioridadmanual_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='proyectos',
            field=models.TextField(blank=True, null=True, verbose_name='Proyectos (Comas)'),
        ),
    ]
