# Generated by Django 5.2.11 on 2026-03-12 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_scenario_proyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoPrioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=50, verbose_name='Proyecto (Formula)')),
                ('prioridad', models.IntegerField(default=999, verbose_name='Prioridad')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_prioridades', to='produccion.scenario', verbose_name='Escenario')),
            ],
            options={
                'verbose_name': 'Prioridad de Proyecto',
                'verbose_name_plural': 'Prioridades de Proyectos',
                'db_table': 'proyecto_prioridad',
                'managed': True,
                'unique_together': {('proyecto', 'scenario')},
            },
        ),
    ]
