# Generated by Django 5.2.11 on 2026-03-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_proyectoprioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo (Ej: Reparación, Preventivo)')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin Estimada')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de Mantenimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='produccion.maquinaconfig', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Máquina',
                'verbose_name_plural': 'Mantenimientos de Máquinas',
                'db_table': 'mantenimiento_maquina',
                'ordering': ['-fecha_inicio'],
                'managed': True,
            },
        ),
    ]
