# Generated by Django 5.2.11 on 2026-03-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_mantenimientomaquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('FALLA', 'Falla No Planificada'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mantenimientomaquina',
            name='motivo',
            field=models.CharField(max_length=200, verbose_name='Motivo (Ej: Reparación, Preventivo, Falla)'),
        ),
    ]
