# Generated by Django 5.2.11 on 2026-04-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_add_falla_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_eficiencia', models.FloatField(default=1.0, help_text='Multiplicador de tiempo (Ej: 1.2 = 20% más lento)')),
                ('maquina_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_destino', to='produccion.maquinaconfig')),
                ('maquina_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_origen', to='produccion.maquinaconfig')),
            ],
            options={
                'verbose_name': 'Equivalencia de Máquina',
                'verbose_name_plural': 'Equivalencias de Máquinas',
                'db_table': 'maquina_equivalencia',
                'managed': True,
                'unique_together': {('maquina_origen', 'maquina_destino')},
            },
        ),
    ]
