# Generated by Django 5.2.11 on 2026-04-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_maquinaequivalencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiddentask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='hiddentask',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_tasks', to='produccion.scenario', verbose_name='Escenario'),
        ),
        migrations.AlterField(
            model_name='hiddentask',
            name='id_orden',
            field=models.BigIntegerField(db_column='IdOrden', verbose_name='ID de Orden'),
        ),
        migrations.AlterUniqueTogether(
            name='hiddentask',
            unique_together={('id_orden', 'scenario')},
        ),
    ]
