# Generated by Django 5.2.11 on 2026-04-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_hiddentask_id_hiddentask_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadmanual',
            name='cantidad_producida_manual',
            field=models.FloatField(blank=True, null=True, verbose_name='Cantidad Producida Manual'),
        ),
    ]
