# Generated by Django 5.2.11 on 2026-04-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0019_prioridadmanual_cantidad_producida_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden', models.BigIntegerField(db_column='IdOrden', verbose_name='ID de Orden (OP)')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_tasks', to='produccion.scenario', verbose_name='Escenario')),
            ],
            options={
                'verbose_name': 'Tarea Planificada',
                'verbose_name_plural': 'Tareas Planificadas',
                'db_table': 'planned_task',
                'managed': True,
                'unique_together': {('id_orden', 'scenario')},
            },
        ),
    ]
