# Generated by Django 5.2.11 on 2026-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0020_plannedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtask',
            name='proyecto_code',
            field=models.CharField(blank=True, help_text='Código del proyecto al que pertenece esta OP (ej: 26-018)', max_length=50, null=True, verbose_name='Código de Proyecto'),
        ),
    ]
