# Generated by Django 5.2.11 on 2026-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0021_add_proyecto_code_to_planned_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtask',
            name='prioridad_pieza',
            field=models.IntegerField(default=1, help_text='Nivel de precedencia de la pieza dentro del proyecto', verbose_name='Prioridad de Pieza'),
        ),
    ]
