# Generated by Django 5.2.11 on 2026-05-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0022_plannedtask_prioridad_pieza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedtask',
            name='prioridad_pieza',
        ),
    ]
