# Generated by Django 5.2.11 on 2026-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0023_remove_plannedtask_prioridad_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadmanual',
            name='orden_secuencia',
            field=models.IntegerField(default=0, verbose_name='Orden Secuencia'),
        ),
    ]
