# Generated by Django 5.2.11 on 2026-05-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0024_prioridadmanual_orden_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtask',
            name='enviado_a_gantt',
            field=models.BooleanField(default=False, help_text='Indica si esta tarea fue congelada/enviada al Gantt', verbose_name='Enviado a Gantt'),
        ),
    ]
