# Generated by Django 5.2.11 on 2026-06-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0025_plannedtask_enviado_a_gantt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridadmanual',
            name='modo_solapamiento',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='automatico', max_length=20, verbose_name='Modo Solapamiento'),
        ),
    ]
