# Generated by Django 5.2.11 on 2026-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0026_prioridadmanual_modo_solapamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
